# Generated by Django 4.1.7 on 2023-03-28 13:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_favorites_alter_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
